# Generated by Django 2.1.3 on 2020-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20200420_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True, default='', verbose_name='任务id')),
                ('interface_id', models.IntegerField(default='', verbose_name='接口id')),
            ],
        ),
    ]
